package newcalculator;

public class CalculatorFrame extends javax.swing.JFrame {
    Calculator Calc;
    private double firstOp=0;
    private double secondOp=0;
    private char operator;
    boolean flag = false;
    boolean equal = false;
    boolean emptyScreen = true;
    
    
    public void print(){
        System.out.println(Screen.getText());
    }


    public CalculatorFrame() {
        Calc = new Calculator();
        initComponents();
        Screen.setText("0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CalculatorPnl = new javax.swing.JPanel();
        Button7 = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonDecimal = new javax.swing.JButton();
        ButtonEquals = new javax.swing.JButton();
        ButtonMinus = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        ButtonAdd = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        ButtonMultiply = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        ButtonDivide = new javax.swing.JButton();
        ButtonModulus = new javax.swing.JButton();
        ButtonRoot = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        PlusOrMinus = new javax.swing.JButton();
        ButtonFact = new javax.swing.JButton();
        ButtonPower = new javax.swing.JButton();
        Screen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Calculator ");
        setResizable(false);

        Button7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        ButtonDecimal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonDecimal.setText(".");
        ButtonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDecimalActionPerformed(evt);
            }
        });

        ButtonEquals.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonEquals.setText("=");
        ButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualsActionPerformed(evt);
            }
        });

        ButtonMinus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonMinus.setText("-");
        ButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinusActionPerformed(evt);
            }
        });

        Button1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        Button2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        ButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonAdd.setText("+");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });

        Button4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        Button5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        ButtonMultiply.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonMultiply.setText("X");
        ButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiplyActionPerformed(evt);
            }
        });

        Button8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button9.setText("9");
        Button9.setToolTipText("");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        ButtonDivide.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonDivide.setText("÷");
        ButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivideActionPerformed(evt);
            }
        });

        ButtonModulus.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        ButtonModulus.setText("%");
        ButtonModulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModulusActionPerformed(evt);
            }
        });

        ButtonRoot.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ButtonRoot.setText("√ ");
        ButtonRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRootActionPerformed(evt);
            }
        });

        ButtonClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonClear.setText("C");
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });

        PlusOrMinus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PlusOrMinus.setText("±");
        PlusOrMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusOrMinusActionPerformed(evt);
            }
        });

        ButtonFact.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonFact.setText("x!");
        ButtonFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFactActionPerformed(evt);
            }
        });

        ButtonPower.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ButtonPower.setText("xⁿ");
        ButtonPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPowerActionPerformed(evt);
            }
        });

        Screen.setEditable(false);
        Screen.setBackground(new java.awt.Color(255, 255, 255));
        Screen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalculatorPnlLayout = new javax.swing.GroupLayout(CalculatorPnl);
        CalculatorPnl.setLayout(CalculatorPnlLayout);
        CalculatorPnlLayout.setHorizontalGroup(
            CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(CalculatorPnlLayout.createSequentialGroup()
                    .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(CalculatorPnlLayout.createSequentialGroup()
                            .addComponent(ButtonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CalculatorPnlLayout.createSequentialGroup()
                            .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CalculatorPnlLayout.createSequentialGroup()
                            .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CalculatorPnlLayout.createSequentialGroup()
                            .addComponent(ButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(CalculatorPnlLayout.createSequentialGroup()
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CalculatorPnlLayout.createSequentialGroup()
                    .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(CalculatorPnlLayout.createSequentialGroup()
                            .addComponent(ButtonPower, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ButtonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CalculatorPnlLayout.createSequentialGroup()
                            .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(Screen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CalculatorPnlLayout.createSequentialGroup()
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonModulus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CalculatorPnlLayout.createSequentialGroup()
                        .addComponent(ButtonFact, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlusOrMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102))
        );
        CalculatorPnlLayout.setVerticalGroup(
            CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorPnlLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Screen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonFact, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlusOrMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonModulus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPower, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(CalculatorPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CalculatorPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
       if(!equal && !(Screen.getText().equals("0"))){
         Screen.setText(Screen.getText()+Button7.getText());
       }
       
       else {
         Screen.setText(Button7.getText());
         equal = false;
       }

       
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
    if(!equal && !(Screen.getText().equals("0"))){
         Screen.setText(Screen.getText()+Button9.getText());
       }
       
       else {
         Screen.setText(Button9.getText());
         equal = false;
       }
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
    if(!equal && !(Screen.getText().equals("0"))){
         Screen.setText(Screen.getText()+Button8.getText());
       }
       
       else {
         Screen.setText(Button8.getText());
         equal = false;
       }
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        if(!equal && !(Screen.getText().equals("0"))){
         Screen.setText(Screen.getText()+Button6.getText());
       }
       
       else {
         Screen.setText(Button6.getText());
         equal = false;
       }
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        if(!equal && !(Screen.getText().equals("0"))){
         Screen.setText(Screen.getText()+Button5.getText());
       }
       
       else {
         Screen.setText(Button5.getText());
         equal = false;
       }
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        if(!equal && !(Screen.getText().equals("0"))){
         Screen.setText(Screen.getText()+Button4.getText());
       }
       
       else {
         Screen.setText(Button4.getText());
         equal = false;
       }
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        if(!equal && !(Screen.getText().equals("0"))){
         Screen.setText(Screen.getText()+Button3.getText());
       }
       
       else {
         Screen.setText(Button3.getText());
         equal = false;
       }
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        if(!equal && !(Screen.getText().equals("0"))){
         Screen.setText(Screen.getText()+Button1.getText());
       }
       
       else {
         Screen.setText(Button1.getText());
         equal = false;
       }
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
       if(!equal && !(Screen.getText().equals("0"))){
         Screen.setText(Screen.getText()+Button2.getText());
       }
       
       else {
         Screen.setText(Button2.getText());
         equal = false;
       }
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        if(!equal && !(Screen.getText().equals("0"))){
         Screen.setText(Screen.getText()+Button0.getText());
       }
       
       else {
         Screen.setText(Button0.getText());
         equal = false;
       }
        
    }//GEN-LAST:event_Button0ActionPerformed

    private void ButtonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDecimalActionPerformed
        
        if(Screen.getText().equals(""))
        {
            Screen.setText(Screen.getText()+"");
        }
        
        else if(!Screen.getText().contains("."))
        {
            Screen.setText(Screen.getText()+".");
        }
        
               
    }//GEN-LAST:event_ButtonDecimalActionPerformed

    private void ButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivideActionPerformed
        if(!Screen.getText().equals(""))
        {    
            firstOp = Double.parseDouble(Screen.getText());
            operator = '/';
            Screen.setText("");
            flag= false;
        }
        operator = '/';
    }//GEN-LAST:event_ButtonDivideActionPerformed

    private void ButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualsActionPerformed
        
        try{
            if(!Screen.getText().equals(""))
            {
                secondOp= Double.parseDouble(Screen.getText());
                flag= false;
                equal = true;
                   if(operator == '+')
                   {
                       Screen.setText(Calc.addition(firstOp,secondOp)+"");
                       firstOp = Double.parseDouble(Screen.getText());
                       operator = '0';

                   }

                   else if(operator == '-')
                   {
                       Screen.setText(Calc.subtraction(firstOp,secondOp)+"");
                       firstOp = Double.parseDouble(Screen.getText());
                       operator = '0';
                   }

                   else if(operator == '*')
                   {
                       Screen.setText(Calc.multiplication(firstOp,secondOp)+"");
                       firstOp = Double.parseDouble(Screen.getText());
                       operator = '0';
                   }

                   else if(operator == '/')
                   {
                       Screen.setText(Calc.division(firstOp,secondOp)+"");
                       firstOp = Double.parseDouble(Screen.getText());
                       operator = '0';
                   }

                    else if(operator == '%')
                   {
                       Screen.setText(Calc.modulus(firstOp,secondOp)+"");
                       firstOp = Double.parseDouble(Screen.getText());
                       operator = '0';
                   }

                   else if(operator == 's')
                   {
                       Screen.setText(Calc.root(firstOp)+"");
                       firstOp = Double.parseDouble(Screen.getText());
                       operator = '0';
                   }

                   else if(operator == '!')
                   {
                       Screen.setText(Calc.factorial(firstOp)+"");
                       firstOp = Double.parseDouble(Screen.getText());
                       operator = '0';

                   }

                   else if (operator == '^')
                   {
                       Screen.setText(Calc.power(firstOp,secondOp)+"");
                       firstOp = Double.parseDouble(Screen.getText());
                       operator = '0';
                   }

                   else
                        Screen.setText(firstOp+"");

            }
        }
        catch(Exception e)
        {
            
        }
    
    }//GEN-LAST:event_ButtonEqualsActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        if(!Screen.getText().equals(""))
        {
            firstOp = Double.parseDouble(Screen.getText());
            operator = '+';
            Screen.setText("");
            //flag= false;
        }
        operator = '+';
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void ButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplyActionPerformed
       if(!Screen.getText().equals(""))
        {
            firstOp = Double.parseDouble(Screen.getText());
            operator = '*';
            Screen.setText("");
            //flag= false;
        }
       operator = '*';
    }//GEN-LAST:event_ButtonMultiplyActionPerformed

    private void ButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinusActionPerformed
      
       
        if(!Screen.getText().equals(""))
        {            
            firstOp = Double.parseDouble(Screen.getText());
            operator = '-';
            Screen.setText("");
            //flag= false;
        }
        operator = '-';
    }//GEN-LAST:event_ButtonMinusActionPerformed

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
       Screen.setText("0");
       //flag= false;
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void ButtonModulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModulusActionPerformed
        if(!Screen.getText().equals(""))
        {
            firstOp = Double.parseDouble(Screen.getText());
            operator = '%';
            Screen.setText("");
            //flag= false;
        }
        operator = '%';
    }//GEN-LAST:event_ButtonModulusActionPerformed

    private void ButtonRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRootActionPerformed
        try{
            if(!Screen.getText().equals(""))
            {
                firstOp = Double.parseDouble(Screen.getText());
                operator = 's';
                Screen.setText(Calc.root(firstOp)+"");
                firstOp = Double.parseDouble(Screen.getText());
                flag= false;
            }
            operator = 's';
        }
        catch(Exception e){}
    }//GEN-LAST:event_ButtonRootActionPerformed

    private void ButtonFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFactActionPerformed
       try{
            if(!Screen.getText().equals(""))
            {
                firstOp = Double.parseDouble(Screen.getText());
                operator = '!';
                Screen.setText(Calc.factorial(firstOp)+"");
                firstOp = Double.parseDouble(Screen.getText());
                flag= false;
            }
           operator = '!';
           }
       catch(Exception e){}
    }//GEN-LAST:event_ButtonFactActionPerformed

    private void ButtonPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPowerActionPerformed
        if(!Screen.getText().equals(""))
        {
            firstOp = Double.parseDouble(Screen.getText());
            operator = '^';
            Screen.setText("");
            flag= false;
        }
        operator = '^';
    }//GEN-LAST:event_ButtonPowerActionPerformed

    private void PlusOrMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusOrMinusActionPerformed
        if(!Screen.getText().equals(""))
        {
            double value = Double.parseDouble(Screen.getText());
            value *= -1;
            Screen.setText(""+value);
            flag= false;  
        }
         
    }//GEN-LAST:event_PlusOrMinusActionPerformed

    private void ScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScreenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonDecimal;
    private javax.swing.JButton ButtonDivide;
    private javax.swing.JButton ButtonEquals;
    private javax.swing.JButton ButtonFact;
    private javax.swing.JButton ButtonMinus;
    private javax.swing.JButton ButtonModulus;
    private javax.swing.JButton ButtonMultiply;
    private javax.swing.JButton ButtonPower;
    private javax.swing.JButton ButtonRoot;
    private javax.swing.JPanel CalculatorPnl;
    private javax.swing.JButton PlusOrMinus;
    private javax.swing.JTextField Screen;
    // End of variables declaration//GEN-END:variables
}
